# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Dockerfile for Token Minter MCP
FROM node:18-alpine

# Create app directory
WORKDIR /app

# Install server dependencies
COPY server/package.json server/yarn.lock ./server/
WORKDIR /app/server
RUN npm install --production

# Copy server code and required artifacts
WORKDIR /app
COPY server ./server
COPY artifacts ./artifacts
COPY contracts ./contracts

# Default to stdio transport of MCP
WORKDIR /app
CMD ["node", "server/index.js"]
